apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: angular
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: angular 
        image: nimnambi/sense-frontend
        ports: 
        - containerPort: 4200 
--- 

kind: Service 
apiVersion: v1 
metadata: 
  name: angular-svc
spec: 
  selector: 
    app: angular 
  ports: 
  - protocol: TCP 
    port: 4200
    targetPort: 4200 
  type: LoadBalancer 
